name: Semantic version Pipeline
on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    if: github.event.head_commit.author.name != 'semantic-release-bot'
    permissions:
      contents: write
      pull-requests: write
      issues: write
    env:
      GITHUB_TOKEN: ${{ secrets.DEPLOY_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.10.0
      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json', '**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      # - name: Run Semantic Release
        # env:
        #   GITHUB_TOKEN: ${{ secrets.DEPLOY_KEY }}
        # run: npx semantic-release@25 --extends ./.releaserc.release.json
      - name: Tag Commit
        id: tag-commit
        uses: issue-ops/semver@v2.6.0
        with:
          manifest-path: package.json
          workspace: ${{ github.workspace }}
          ref: master
